# themes.py

from colors import COLORS

THEMES = {
    "aquatic": {
        "background_color": COLORS["DEEP_AQUATIC_BLUE"],
        "done_button_color": COLORS["MEDIUM_TURQUOISE"],
        "add_tasks_choose_folder_color": COLORS["LIGHT_SEA_GREEN"],
        "add_tasks_chosen_folder_color": COLORS["DEEP_SKY_BLUE"],
        "complete_tasks_hub_folder_color": COLORS["DARK_CYAN"],
        "complete_tasks_task_color": COLORS["AQUAMARINE"],
        "remove_tasks_hub_folder_color": COLORS["BLUE_LAGOON"],
        "remove_tasks_task_color": COLORS["TURQUOISE"],
        "add_spoons_color": COLORS["DEEP_SKY_BLUE"],
        "add_tasks_color": COLORS["DARK_CYAN"],
        "complete_tasks_color": COLORS["AQUAMARINE"],
        "remove_tasks_color": COLORS["TURQUOISE"],
        "daily_schedule_color": COLORS["LIGHT_SEA_GREEN"],
        "calendar_color": COLORS["BLUE_LAGOON"],
        "settings_color": COLORS["DEEP_AQUATIC_BLUE"],
        "calendar_current_day_color": COLORS["DEEP_AQUATIC_BLUE"],
        "calendar_current_day_header_color": COLORS["MEDIUM_TURQUOISE"],
        "calendar_previous_day_color": COLORS["LIGHT_SEA_GREEN"],
        "calendar_previous_day_header_color": COLORS["DEEP_SKY_BLUE"],
        "calendar_next_day_color": COLORS["AQUAMARINE"],
        "calendar_next_day_header_color": COLORS["DARK_CYAN"],
        "calendar_month_color": COLORS["BLUE_LAGOON"],
        "homework_fol_color": COLORS["DEEP_AQUATIC_BLUE"],
        "chores_fol_color": COLORS["MEDIUM_TURQUOISE"],
        "work_fol_color": COLORS["DEEP_SKY_BLUE"],
        "misc_fol_color": COLORS["TURQUOISE"],
    },
    "foresty": {
        "background_color": COLORS["DARK_OLIVE_GREEN"],
        "done_button_color": COLORS["OLIVE_DRAB"],
        "add_tasks_choose_folder_color": COLORS["DARK_SEA_GREEN"],
        "add_tasks_chosen_folder_color": COLORS["SILVER_SAGE"],
        "complete_tasks_hub_folder_color": COLORS["MEDIUM_SEA_GREEN"],
        "complete_tasks_task_color": COLORS["PALE_GREEN"],
        "remove_tasks_hub_folder_color": COLORS["FOREST_GREEN"],
        "remove_tasks_task_color": COLORS["LAWN_GREEN"],
        "add_spoons_color": COLORS["OLIVE_DRAB"],
        "add_tasks_color": COLORS["DARK_SEA_GREEN"],
        "complete_tasks_color": COLORS["FOREST_GREEN"],
        "remove_tasks_color": COLORS["FOREST_GREEN"],
        "daily_schedule_color": COLORS["MEDIUM_SEA_GREEN"],
        "calendar_color": COLORS["LAWN_GREEN"],
        "settings_color": COLORS["SEAFOAM_GREEN"],
        "calendar_current_day_color": COLORS["DARK_OLIVE_GREEN"],
        "calendar_current_day_header_color": COLORS["OLIVE_DRAB"],
        "calendar_previous_day_color": COLORS["DARK_SEA_GREEN"],
        "calendar_previous_day_header_color": COLORS["MEDIUM_SEA_GREEN"],
        "calendar_next_day_color": COLORS["PALE_GREEN"],
        "calendar_next_day_header_color": COLORS["FOREST_GREEN"],
        "calendar_month_color": COLORS["DARK_OLIVE_GREEN"],
        "homework_fol_color": COLORS["OLIVE_DRAB"],
        "chores_fol_color": COLORS["DARK_SEA_GREEN"],
        "work_fol_color": COLORS["FOREST_GREEN"],
        "misc_fol_color": COLORS["MEDIUM_SEA_GREEN"],
    },
    "girly_pop": {
        "background_color": COLORS["LIGHT_PINK"],
        "done_button_color": COLORS["LAVENDER_BLUSH"],
        "add_tasks_choose_folder_color": COLORS["PALE_VIOLET_RED"],
        "add_tasks_chosen_folder_color": COLORS["LAVENDER"],
        "complete_tasks_hub_folder_color": COLORS["PLUM"],
        "complete_tasks_task_color": COLORS["ANTIQUE_WHITE"],
        "remove_tasks_hub_folder_color": COLORS["LIGHT_SALMON"],
        "remove_tasks_task_color": COLORS["MISTY_ROSE"],
        "add_spoons_color": COLORS["LAVENDER_BLUSH"],
        "add_tasks_color": COLORS["PALE_VIOLET_RED"],
        "complete_tasks_color": COLORS["ANTIQUE_WHITE"],
        "remove_tasks_color": COLORS["LIGHT_SALMON"],
        "daily_schedule_color": COLORS["LAVENDER"],
        "calendar_color": COLORS["PLUM"],
        "settings_color": COLORS["LIGHT_PINK"],
        "calendar_current_day_color": COLORS["LIGHT_PINK"],
        "calendar_current_day_header_color": COLORS["LAVENDER_BLUSH"],
        "calendar_previous_day_color": COLORS["PALE_VIOLET_RED"],
        "calendar_previous_day_header_color": COLORS["LAVENDER"],
        "calendar_next_day_color": COLORS["PLUM"],
        "calendar_next_day_header_color": COLORS["ANTIQUE_WHITE"],
        "calendar_month_color": COLORS["LIGHT_PINK"],
        "homework_fol_color": COLORS["PALE_VIOLET_RED"],
        "chores_fol_color": COLORS["LAVENDER_BLUSH"],
        "work_fol_color": COLORS["PLUM"],
        "misc_fol_color": COLORS["MISTY_ROSE"],
    },
    "vampire_goth": {
        "background_color": COLORS["CRIMSON_RED"],
        "done_button_color": COLORS["INDIGO"],
        "add_tasks_choose_folder_color": COLORS["DARK_SLATE_GRAY"],
        "add_tasks_chosen_folder_color": COLORS["DIM_GRAY"],
        "complete_tasks_hub_folder_color": COLORS["MAROON"],
        "complete_tasks_task_color": COLORS["DARK_RED"],
        "remove_tasks_hub_folder_color": COLORS["DARK_SLATE_BLUE"],
        "remove_tasks_task_color": COLORS["DARK_SLATE_GRAY"],
        "add_spoons_color": COLORS["INDIGO"],
        "add_tasks_color": COLORS["DARK_SLATE_GRAY"],
        "complete_tasks_color": COLORS["DARK_RED"],
        "remove_tasks_color": COLORS["DARK_SLATE_BLUE"],
        "daily_schedule_color": COLORS["DIM_GRAY"],
        "calendar_color": COLORS["MAROON"],
        "settings_color": COLORS["CRIMSON_RED"],
        "calendar_current_day_color": COLORS["CRIMSON_RED"],
        "calendar_current_day_header_color": COLORS["INDIGO"],
        "calendar_previous_day_color": COLORS["DARK_SLATE_GRAY"],
        "calendar_previous_day_header_color": COLORS["DIM_GRAY"],
        "calendar_next_day_color": COLORS["MAROON"],
        "calendar_next_day_header_color": COLORS["DARK_RED"],
        "calendar_month_color": COLORS["CRIMSON_RED"],
        "homework_fol_color": COLORS["INDIGO"],
        "chores_fol_color": COLORS["DARK_SLATE_GRAY"],
        "work_fol_color": COLORS["MAROON"],
        "misc_fol_color": COLORS["DARK_SLATE_GRAY"],
    },
    "sunset_glow": {
        "background_color": COLORS["DARK_ORANGE"],
        "done_button_color": COLORS["RED_ORANGE"],
        "add_tasks_choose_folder_color": COLORS["ORANGE"],
        "add_tasks_chosen_folder_color": COLORS["TOMATO"],
        "complete_tasks_hub_folder_color": COLORS["CORAL"],
        "complete_tasks_task_color": COLORS["GOLD"],
        "remove_tasks_hub_folder_color": COLORS["LIGHT_PINK"],
        "remove_tasks_task_color": COLORS["LIGHT_SALMON"],
        "add_spoons_color": COLORS["TOMATO"],
        "add_tasks_color": COLORS["ORANGE"],
        "complete_tasks_color": COLORS["CORAL"],
        "remove_tasks_color": COLORS["LIGHT_SALMON"],
        "daily_schedule_color": COLORS["GOLD"],
        "calendar_color": COLORS["DARK_ORANGE"],
        "settings_color": COLORS["RED_ORANGE"],
        "calendar_current_day_color": COLORS["DARK_ORANGE"],
        "calendar_current_day_header_color": COLORS["RED_ORANGE"],
        "calendar_previous_day_color": COLORS["ORANGE"],
        "calendar_previous_day_header_color": COLORS["TOMATO"],
        "calendar_next_day_color": COLORS["CORAL"],
        "calendar_next_day_header_color": COLORS["GOLD"],
        "calendar_month_color": COLORS["DARK_ORANGE"],
        "homework_fol_color": COLORS["RED_ORANGE"],
        "chores_fol_color": COLORS["ORANGE"],
        "work_fol_color": COLORS["CORAL"],
        "misc_fol_color": COLORS["LIGHT_SALMON"],
    },
    "light_academia": {
        "background_color": COLORS["BACKGROUND_IMAGE"],
        "hub_background_color": COLORS["SOFT_BEIGE"],
        "done_button_color": COLORS["MUTED_BROWN"],
        "add_tasks_choose_folder_color": COLORS["LIGHT_IVORY"],
        "add_tasks_chosen_folder_color": COLORS["SOFT_TAUPE"],
        "complete_tasks_hub_folder_color": COLORS["WARM_GREY"],
        "complete_tasks_task_color": COLORS["SAGE_GREEN"],
        "remove_tasks_hub_folder_color": COLORS["DARK_OLIVE"],
        "remove_tasks_task_color": COLORS["SAGE_GREEN"],
        "add_spoons_color": COLORS["SOFT_TAUPE"],
        "add_tasks_color": COLORS["WARM_GREY"],
        "complete_tasks_color": COLORS["SAGE_GREEN"],
        "remove_tasks_color": COLORS["SAGE_GREEN"],
        "daily_schedule_color": COLORS["LIGHT_IVORY"],
        "calendar_color": COLORS["WARM_GREY"],
        "settings_color": COLORS["SOFT_BEIGE"],
        "calendar_current_day_color": COLORS["SOFT_BEIGE"],
        "calendar_current_day_header_color": COLORS["MUTED_BROWN"],
        "calendar_previous_day_color": COLORS["LIGHT_IVORY"],
        "calendar_previous_day_header_color": COLORS["SOFT_TAUPE"],
        "calendar_next_day_color": COLORS["SAGE_GREEN"],
        "calendar_next_day_header_color": COLORS["WARM_GREY"],
        "calendar_month_color": COLORS["SAGE_GREEN"],
        "homework_fol_color": COLORS["SOFT_BEIGE"],
        "chores_fol_color": COLORS["MUTED_BROWN"],
        "work_fol_color": COLORS["SOFT_TAUPE"],
        "misc_fol_color": COLORS["SAGE_GREEN"],
    },
    "retro": {
        "background_color": COLORS["VINTAGE_ORANGE"],
        "done_button_color": COLORS["MUSTARD_YELLOW"],
        "add_tasks_choose_folder_color": COLORS["TEAL"],
        "add_tasks_chosen_folder_color": COLORS["TURQUOISE"],
        "complete_tasks_hub_folder_color": COLORS["PEACH"],
        "complete_tasks_task_color": COLORS["MINT_GREEN"],
        "remove_tasks_hub_folder_color": COLORS["BROWN"],
        "remove_tasks_task_color": COLORS["TANGERINE"],
        "add_spoons_color": COLORS["MUSTARD_YELLOW"],
        "add_tasks_color": COLORS["PEACH"],
        "complete_tasks_color": COLORS["MINT_GREEN"],
        "remove_tasks_color": COLORS["TANGERINE"],
        "daily_schedule_color": COLORS["VINTAGE_ORANGE"],
        "calendar_color": COLORS["BROWN"],
        "settings_color": COLORS["TEAL"],
        "calendar_current_day_color": COLORS["VINTAGE_ORANGE"],
        "calendar_current_day_header_color": COLORS["MUSTARD_YELLOW"],
        "calendar_previous_day_color": COLORS["PEACH"],
        "calendar_previous_day_header_color": COLORS["MINT_GREEN"],
        "calendar_next_day_color": COLORS["TURQUOISE"],
        "calendar_next_day_header_color": COLORS["BROWN"],
        "calendar_month_color": COLORS["TANGERINE"],
        "homework_fol_color": COLORS["VINTAGE_ORANGE"],
        "chores_fol_color": COLORS["MUSTARD_YELLOW"],
        "work_fol_color": COLORS["TURQUOISE"],
        "misc_fol_color": COLORS["TANGERINE"],
    },
    "minimalist": {
        "background_color": COLORS["WHITE"],
        "done_button_color": COLORS["LIGHT_GRAY"],
        "add_tasks_choose_folder_color": COLORS["SOFT_BLACK"],
        "add_tasks_chosen_folder_color": COLORS["WHITE"],
        "complete_tasks_hub_folder_color": COLORS["DARK_GRAY"],
        "complete_tasks_task_color": COLORS["LIGHT_GRAY"],
        "remove_tasks_hub_folder_color": COLORS["SOFT_BLACK"],
        "remove_tasks_task_color": COLORS["WHITE"],
        "add_spoons_color": COLORS["DARK_GRAY"],
        "add_tasks_color": COLORS["SOFT_BLACK"],
        "complete_tasks_color": COLORS["LIGHT_GRAY"],
        "remove_tasks_color": COLORS["WHITE"],
        "daily_schedule_color": COLORS["LIGHT_GRAY"],
        "calendar_color": COLORS["DARK_GRAY"],
        "settings_color": COLORS["WHITE"],
        "calendar_current_day_color": COLORS["WHITE"],
        "calendar_current_day_header_color": COLORS["LIGHT_GRAY"],
        "calendar_previous_day_color": COLORS["SOFT_BLACK"],
        "calendar_previous_day_header_color": COLORS["DARK_GRAY"],
        "calendar_next_day_color": COLORS["LIGHT_GRAY"],
        "calendar_next_day_header_color": COLORS["SOFT_BLACK"],
        "calendar_month_color": COLORS["DARK_GRAY"],
        "homework_fol_color": COLORS["WHITE"],
        "chores_fol_color": COLORS["LIGHT_GRAY"],
        "work_fol_color": COLORS["SOFT_BLACK"],
        "misc_fol_color": COLORS["DARK_GRAY"],
    },
    "cosmic": {
        "background_color": COLORS["DEEP_SPACE_PURPLE"],
        "done_button_color": COLORS["STARDUST_SILVER"],
        "add_tasks_choose_folder_color": COLORS["GALACTIC_BLUE"],
        "add_tasks_chosen_folder_color": COLORS["NEBULA_PINK"],
        "complete_tasks_hub_folder_color": COLORS["BLACK_HOLE"],
        "complete_tasks_task_color": COLORS["STARFIRE_YELLOW"],
        "remove_tasks_hub_folder_color": COLORS["COSMIC_RED"],
        "remove_tasks_task_color": COLORS["NEON_GREEN"],
        "add_spoons_color": COLORS["NEBULA_PINK"],
        "add_tasks_color": COLORS["BLACK_HOLE"],
        "complete_tasks_color": COLORS["STARFIRE_YELLOW"],
        "remove_tasks_color": COLORS["NEON_GREEN"],
        "daily_schedule_color": COLORS["GALACTIC_BLUE"],
        "calendar_color": COLORS["BLACK_HOLE"],
        "settings_color": COLORS["DEEP_SPACE_PURPLE"],
        "calendar_current_day_color": COLORS["DEEP_SPACE_PURPLE"],
        "calendar_current_day_header_color": COLORS["STARDUST_SILVER"],
        "calendar_previous_day_color": COLORS["GALACTIC_BLUE"],
        "calendar_previous_day_header_color": COLORS["NEBULA_PINK"],
        "calendar_next_day_color": COLORS["STARFIRE_YELLOW"],
        "calendar_next_day_header_color": COLORS["COSMIC_RED"],
        "calendar_month_color": COLORS["NEON_GREEN"],
        "homework_fol_color": COLORS["DEEP_SPACE_PURPLE"],
        "chores_fol_color": COLORS["STARDUST_SILVER"],
        "work_fol_color": COLORS["NEBULA_PINK"],
        "misc_fol_color": COLORS["COSMIC_RED"],
    },
    "autumn_harvest": {
        "background_color": COLORS["RUST"],
        "done_button_color": COLORS["DEEP_ORANGE"],
        "add_tasks_choose_folder_color": COLORS["GOLDEN_YELLOW"],
        "add_tasks_chosen_folder_color": COLORS["BROWN"],
        "complete_tasks_hub_folder_color": COLORS["CRIMSON"],
        "complete_tasks_task_color": COLORS["BURNISHED_RED"],
        "remove_tasks_hub_folder_color": COLORS["BURNISHED_ORANGE"],
        "remove_tasks_task_color": COLORS["TERRACOTTA"],
        "add_spoons_color": COLORS["GOLDEN_YELLOW"],
        "add_tasks_color": COLORS["CRIMSON"],
        "complete_tasks_color": COLORS["BURNISHED_RED"],
        "remove_tasks_color": COLORS["TERRACOTTA"],
        "daily_schedule_color": COLORS["RUST"],
        "calendar_color": COLORS["BROWN"],
        "settings_color": COLORS["RUST"],
        "calendar_current_day_color": COLORS["RUST"],
        "calendar_current_day_header_color": COLORS["DEEP_ORANGE"],
        "calendar_previous_day_color": COLORS["GOLDEN_YELLOW"],
        "calendar_previous_day_header_color": COLORS["BROWN"],
        "calendar_next_day_color": COLORS["BURNISHED_RED"],
        "calendar_next_day_header_color": COLORS["CRIMSON"],
        "calendar_month_color": COLORS["TERRACOTTA"],
        "homework_fol_color": COLORS["RUST"],
        "chores_fol_color": COLORS["DEEP_ORANGE"],
        "work_fol_color": COLORS["BROWN"],
        "misc_fol_color": COLORS["TERRACOTTA"],
    },
    "tropical_oasis": {
        "background_color": COLORS["TURQUOISE"],
        "done_button_color": COLORS["VIBRANT_CORAL"],
        "add_tasks_choose_folder_color": COLORS["SUNSHINE_YELLOW"],
        "add_tasks_chosen_folder_color": COLORS["LUSH_GREEN"],
        "complete_tasks_hub_folder_color": COLORS["DEEP_BLUE"],
        "complete_tasks_task_color": COLORS["CORAL_PINK"],
        "remove_tasks_hub_folder_color": COLORS["AQUA_BLUE"],
        "remove_tasks_task_color": COLORS["SEAFOAM_GREEN"],
        "add_spoons_color": COLORS["SUNSHINE_YELLOW"],
        "add_tasks_color": COLORS["DEEP_BLUE"],
        "complete_tasks_color": COLORS["CORAL_PINK"],
        "remove_tasks_color": COLORS["SEAFOAM_GREEN"],
        "daily_schedule_color": COLORS["LUSH_GREEN"],
        "calendar_color": COLORS["AQUA_BLUE"],
        "settings_color": COLORS["TURQUOISE"],
        "calendar_current_day_color": COLORS["TURQUOISE"],
        "calendar_current_day_header_color": COLORS["VIBRANT_CORAL"],
        "calendar_previous_day_color": COLORS["SUNSHINE_YELLOW"],
        "calendar_previous_day_header_color": COLORS["LUSH_GREEN"],
        "calendar_next_day_color": COLORS["CORAL_PINK"],
        "calendar_next_day_header_color": COLORS["DEEP_BLUE"],
        "calendar_month_color": COLORS["SEAFOAM_GREEN"],
        "homework_fol_color": COLORS["TURQUOISE"],
        "chores_fol_color": COLORS["VIBRANT_CORAL"],
        "work_fol_color": COLORS["LUSH_GREEN"],
        "misc_fol_color": COLORS["SEAFOAM_GREEN"],
    },
    "pastel_dreams": {
        "background_color": COLORS["PALE_PINK"],
        "done_button_color": COLORS["PASTEL_LAVENDER"],
        "add_tasks_choose_folder_color": COLORS["PALE_MINT"],
        "add_tasks_chosen_folder_color": COLORS["BABY_BLUE"],
        "complete_tasks_hub_folder_color": COLORS["PASTEL_YELLOW"],
        "complete_tasks_task_color": COLORS["PASTEL_PINK"],
        "remove_tasks_hub_folder_color": COLORS["PALE_LAVENDER"],
        "remove_tasks_task_color": COLORS["MINT_GREEN"],
        "add_spoons_color": COLORS["PASTEL_LAVENDER"],
        "add_tasks_color": COLORS["PALE_MINT"],
        "complete_tasks_color": COLORS["PASTEL_PINK"],
        "remove_tasks_color": COLORS["MINT_GREEN"],
        "daily_schedule_color": COLORS["PALE_PINK"],
        "calendar_color": COLORS["PASTEL_YELLOW"],
        "settings_color": COLORS["PALE_PINK"],
        "calendar_current_day_color": COLORS["PALE_PINK"],
        "calendar_current_day_header_color": COLORS["PASTEL_LAVENDER"],
        "calendar_previous_day_color": COLORS["PALE_MINT"],
        "calendar_previous_day_header_color": COLORS["BABY_BLUE"],
        "calendar_next_day_color": COLORS["PASTEL_PINK"],
        "calendar_next_day_header_color": COLORS["PASTEL_YELLOW"],
        "calendar_month_color": COLORS["MINT_GREEN"],
        "homework_fol_color": COLORS["PALE_PINK"],
        "chores_fol_color": COLORS["PASTEL_LAVENDER"],
        "work_fol_color": COLORS["BABY_BLUE"],
        "misc_fol_color": COLORS["MINT_GREEN"],
    },
    "steampunk": {
        "background_color": COLORS["BRASS"],
        "done_button_color": COLORS["COPPER"],
        "add_tasks_choose_folder_color": COLORS["RUSTED_METAL"],
        "add_tasks_chosen_folder_color": COLORS["STEEL_GREY"],
        "complete_tasks_hub_folder_color": COLORS["GOLDEN_COG"],
        "complete_tasks_task_color": COLORS["ANTIQUE_BROWN"],
        "remove_tasks_hub_folder_color": COLORS["BURNISHED_COPPER"],
        "remove_tasks_task_color": COLORS["VINTAGE_GOLD"],
        "add_spoons_color": COLORS["STEEL_GREY"],
        "add_tasks_color": COLORS["RUSTED_METAL"],
        "complete_tasks_color": COLORS["ANTIQUE_BROWN"],
        "remove_tasks_color": COLORS["VINTAGE_GOLD"],
        "daily_schedule_color": COLORS["BRASS"],
        "calendar_color": COLORS["BURNISHED_COPPER"],
        "settings_color": COLORS["STEEL_GREY"],
        "calendar_current_day_color": COLORS["BRASS"],
        "calendar_current_day_header_color": COLORS["COPPER"],
        "calendar_previous_day_color": COLORS["RUSTED_METAL"],
        "calendar_previous_day_header_color": COLORS["STEEL_GREY"],
        "calendar_next_day_color": COLORS["GOLDEN_COG"],
        "calendar_next_day_header_color": COLORS["ANTIQUE_BROWN"],
        "calendar_month_color": COLORS["VINTAGE_GOLD"],
        "homework_fol_color": COLORS["BRASS"],
        "chores_fol_color": COLORS["COPPER"],
        "work_fol_color": COLORS["STEEL_GREY"],
        "misc_fol_color": COLORS["ANTIQUE_BROWN"],
    },
    "cyberpunk": {
        "background_color": COLORS["NEON_PINK"],
        "done_button_color": COLORS["ELECTRIC_BLUE"],
        "add_tasks_choose_folder_color": COLORS["HACKER_GREEN"],
        "add_tasks_chosen_folder_color": COLORS["LIME_YELLOW"],
        "complete_tasks_hub_folder_color": COLORS["MIDNIGHT_BLACK"],
        "complete_tasks_task_color": COLORS["CYBER_ORANGE"],
        "remove_tasks_hub_folder_color": COLORS["ELECTRIC_PURPLE"],
        "remove_tasks_task_color": COLORS["NEON_TURQUOISE"],
        "add_spoons_color": COLORS["LIME_YELLOW"],
        "add_tasks_color": COLORS["MIDNIGHT_BLACK"],
        "complete_tasks_color": COLORS["CYBER_ORANGE"],
        "remove_tasks_color": COLORS["NEON_TURQUOISE"],
        "daily_schedule_color": COLORS["HACKER_GREEN"],
        "calendar_color": COLORS["MIDNIGHT_BLACK"],
        "settings_color": COLORS["NEON_PINK"],
        "calendar_current_day_color": COLORS["NEON_PINK"],
        "calendar_current_day_header_color": COLORS["ELECTRIC_BLUE"],
        "calendar_previous_day_color": COLORS["HACKER_GREEN"],
        "calendar_previous_day_header_color": COLORS["LIME_YELLOW"],
        "calendar_next_day_color": COLORS["CYBER_ORANGE"],
        "calendar_next_day_header_color": COLORS["ELECTRIC_PURPLE"],
        "calendar_month_color": COLORS["NEON_TURQUOISE"],
        "homework_fol_color": COLORS["NEON_PINK"],
        "chores_fol_color": COLORS["ELECTRIC_BLUE"],
        "work_fol_color": COLORS["LIME_YELLOW"],
        "misc_fol_color": COLORS["CYBER_ORANGE"],
    },
    "rustic_charm": {
        "background_color": COLORS["WARM_BROWN"],
        "done_button_color": COLORS["OAK_WOOD"],
        "add_tasks_choose_folder_color": COLORS["DEEP_GREEN"],
        "add_tasks_chosen_folder_color": COLORS["CREAM_WHITE"],
        "complete_tasks_hub_folder_color": COLORS["DARK_ASH"],
        "complete_tasks_task_color": COLORS["SUNFLOWER_YELLOW"],
        "remove_tasks_hub_folder_color": COLORS["BURGUNDY_RED"],
        "remove_tasks_task_color": COLORS["TERRACOTTA"],
        "add_spoons_color": COLORS["CREAM_WHITE"],
        "add_tasks_color": COLORS["DEEP_GREEN"],
        "complete_tasks_color": COLORS["SUNFLOWER_YELLOW"],
        "remove_tasks_color": COLORS["TERRACOTTA"],
        "daily_schedule_color": COLORS["WARM_BROWN"],
        "calendar_color": COLORS["DARK_ASH"],
        "settings_color": COLORS["WARM_BROWN"],
        "calendar_current_day_color": COLORS["WARM_BROWN"],
        "calendar_current_day_header_color": COLORS["OAK_WOOD"],
        "calendar_previous_day_color": COLORS["DEEP_GREEN"],
        "calendar_previous_day_header_color": COLORS["CREAM_WHITE"],
        "calendar_next_day_color": COLORS["SUNFLOWER_YELLOW"],
        "calendar_next_day_header_color": COLORS["BURGUNDY_RED"],
        "calendar_month_color": COLORS["TERRACOTTA"],
        "homework_fol_color": COLORS["WARM_BROWN"],
        "chores_fol_color": COLORS["OAK_WOOD"],
        "work_fol_color": COLORS["DEEP_GREEN"],
        "misc_fol_color": COLORS["TERRACOTTA"],
    }
}

DROPDOWN_LISTS = {
    "aquatic": {
        "dropdown_colors_list": [
            ["background", COLORS["DEEP_AQUATIC_BLUE"]],
            ["done button", COLORS["MEDIUM_TURQUOISE"]],
            ["folder choices", COLORS["LIGHT_SEA_GREEN"]],
            ["chosen folder", COLORS["DEEP_SKY_BLUE"]],
            ["choose folder C", COLORS["DARK_CYAN"]],
            ["complete task", COLORS["AQUAMARINE"]],
            ["choose folder R", COLORS["BLUE_LAGOON"]],
            ["remove task", COLORS["TURQUOISE"]],
        ],
        "dropdown_hub_colors_list": [
            ["add spoons", COLORS["DEEP_SKY_BLUE"]],
            ["add tasks", COLORS["DARK_CYAN"]],
            ["complete tasks", COLORS["AQUAMARINE"]],
            ["remove tasks", COLORS["TURQUOISE"]],
            ["daily schedule", COLORS["LIGHT_SEA_GREEN"]],
            ["calendar", COLORS["BLUE_LAGOON"]],
            ["settings", COLORS["DEEP_AQUATIC_BLUE"]],
        ],
        "dropdown_calendar_colors_list": [
            ["current day", COLORS["DEEP_AQUATIC_BLUE"]],
            ["cur day header", COLORS["MEDIUM_TURQUOISE"]],
            ["previous day", COLORS["LIGHT_SEA_GREEN"]],
            ["pre day header", COLORS["DEEP_SKY_BLUE"]],
            ["next day", COLORS["AQUAMARINE"]],
            ["next day header", COLORS["DARK_CYAN"]],
            ["month pre/next", COLORS["BLUE_LAGOON"]],
            ["homework fol", COLORS["DEEP_AQUATIC_BLUE"]],
            ["chores fol", COLORS["MEDIUM_TURQUOISE"]],
            ["work fol", COLORS["DEEP_SKY_BLUE"]],
            ["misc fol", COLORS["TURQUOISE"]],
        ],
    },
    "foresty": {
        "dropdown_colors_list": [
            ["background", COLORS["DARK_OLIVE_GREEN"]],
            ["done button", COLORS["OLIVE_DRAB"]],
            ["folder choices", COLORS["DARK_SEA_GREEN"]],
            ["chosen folder", COLORS["SILVER_SAGE"]],
            ["choose folder C", COLORS["MEDIUM_SEA_GREEN"]],
            ["complete task", COLORS["PALE_GREEN"]],
            ["choose folder R", COLORS["FOREST_GREEN"]],
            ["remove task", COLORS["LAWN_GREEN"]],
        ],
        "dropdown_hub_colors_list": [
            ["add spoons", COLORS["OLIVE_DRAB"]],
            ["add tasks", COLORS["DARK_SEA_GREEN"]],
            ["complete tasks", COLORS["PALE_GREEN"]],
            ["remove tasks", COLORS["FOREST_GREEN"]],
            ["daily schedule", COLORS["MEDIUM_SEA_GREEN"]],
            ["calendar", COLORS["LAWN_GREEN"]],
            ["settings", COLORS["DARK_OLIVE_GREEN"]],
        ],
        "dropdown_calendar_colors_list": [
            ["current day", COLORS["DARK_OLIVE_GREEN"]],
            ["cur day header", COLORS["OLIVE_DRAB"]],
            ["previous day", COLORS["DARK_SEA_GREEN"]],
            ["pre day header", COLORS["MEDIUM_SEA_GREEN"]],
            ["next day", COLORS["PALE_GREEN"]],
            ["next day header", COLORS["FOREST_GREEN"]],
            ["month pre/next", COLORS["DARK_OLIVE_GREEN"]],
            ["homework fol", COLORS["OLIVE_DRAB"]],
            ["chores fol", COLORS["DARK_SEA_GREEN"]],
            ["work fol", COLORS["FOREST_GREEN"]],
            ["misc fol", COLORS["MEDIUM_SEA_GREEN"]],
        ],
    },
    "girly_pop": {
        "dropdown_colors_list": [
            ["background", COLORS["LIGHT_PINK"]],
            ["done button", COLORS["LAVENDER_BLUSH"]],
            ["folder choices", COLORS["PALE_VIOLET_RED"]],
            ["chosen folder", COLORS["LAVENDER"]],
            ["choose folder C", COLORS["PLUM"]],
            ["complete task", COLORS["ANTIQUE_WHITE"]],
            ["choose folder R", COLORS["LIGHT_SALMON"]],
            ["remove task", COLORS["MISTY_ROSE"]],
        ],
        "dropdown_hub_colors_list": [
            ["add spoons", COLORS["LAVENDER_BLUSH"]],
            ["add tasks", COLORS["PALE_VIOLET_RED"]],
            ["complete tasks", COLORS["ANTIQUE_WHITE"]],
            ["remove tasks", COLORS["LIGHT_SALMON"]],
            ["daily schedule", COLORS["LAVENDER"]],
            ["calendar", COLORS["PLUM"]],
            ["settings", COLORS["LIGHT_PINK"]],
        ],
        "dropdown_calendar_colors_list": [
            ["current day", COLORS["LIGHT_PINK"]],
            ["cur day header", COLORS["LAVENDER_BLUSH"]],
            ["previous day", COLORS["PALE_VIOLET_RED"]],
            ["pre day header", COLORS["LAVENDER"]],
            ["next day", COLORS["PLUM"]],
            ["next day header", COLORS["ANTIQUE_WHITE"]],
            ["month pre/next", COLORS["LIGHT_PINK"]],
            ["homework fol", COLORS["PALE_VIOLET_RED"]],
            ["chores fol", COLORS["LAVENDER_BLUSH"]],
            ["work fol", COLORS["PLUM"]],
            ["misc fol", COLORS["MISTY_ROSE"]],
        ],
    },
    "vampire_goth": {
        "dropdown_colors_list": [
            ["background", COLORS["CRIMSON_RED"]],
            ["done button", COLORS["INDIGO"]],
            ["folder choices", COLORS["DARK_SLATE_GRAY"]],
            ["chosen folder", COLORS["DIM_GRAY"]],
            ["choose folder C", COLORS["MAROON"]],
            ["complete task", COLORS["DARK_RED"]],
            ["choose folder R", COLORS["DARK_SLATE_BLUE"]],
            ["remove task", COLORS["DARK_SLATE_GRAY"]],
        ],
        "dropdown_hub_colors_list": [
            ["add spoons", COLORS["INDIGO"]],
            ["add tasks", COLORS["DARK_SLATE_GRAY"]],
            ["complete tasks", COLORS["DARK_RED"]],
            ["remove tasks", COLORS["DARK_SLATE_BLUE"]],
            ["daily schedule", COLORS["DIM_GRAY"]],
            ["calendar", COLORS["MAROON"]],
            ["settings", COLORS["CRIMSON_RED"]],
        ],
        "dropdown_calendar_colors_list": [
            ["current day", COLORS["CRIMSON_RED"]],
            ["cur day header", COLORS["INDIGO"]],
            ["previous day", COLORS["DARK_SLATE_GRAY"]],
            ["pre day header", COLORS["DIM_GRAY"]],
            ["next day", COLORS["MAROON"]],
            ["next day header", COLORS["DARK_RED"]],
            ["month pre/next", COLORS["CRIMSON_RED"]],
            ["homework fol", COLORS["INDIGO"]],
            ["chores fol", COLORS["DARK_SLATE_GRAY"]],
            ["work fol", COLORS["MAROON"]],
            ["misc fol", COLORS["DARK_SLATE_GRAY"]],
        ],
    },
    "sunset_glow": {
        "dropdown_colors_list": [
            ["background", COLORS["DARK_ORANGE"]],
            ["done button", COLORS["RED_ORANGE"]],
            ["folder choices", COLORS["ORANGE"]],
            ["chosen folder", COLORS["TOMATO"]],
            ["choose folder C", COLORS["CORAL"]],
            ["complete task", COLORS["GOLD"]],
            ["choose folder R", COLORS["LIGHT_PINK"]],
            ["remove task", COLORS["LIGHT_SALMON"]],
        ],
        "dropdown_hub_colors_list": [
            ["add spoons", COLORS["TOMATO"]],
            ["add tasks", COLORS["ORANGE"]],
            ["complete tasks", COLORS["CORAL"]],
            ["remove tasks", COLORS["LIGHT_SALMON"]],
            ["daily schedule", COLORS["GOLD"]],
            ["calendar", COLORS["DARK_ORANGE"]],
            ["settings", COLORS["RED_ORANGE"]],
        ],
        "dropdown_calendar_colors_list": [
            ["current day", COLORS["DARK_ORANGE"]],
            ["cur day header", COLORS["RED_ORANGE"]],
            ["previous day", COLORS["ORANGE"]],
            ["pre day header", COLORS["TOMATO"]],
            ["next day", COLORS["CORAL"]],
            ["next day header", COLORS["GOLD"]],
            ["month pre/next", COLORS["DARK_ORANGE"]],
            ["homework fol", COLORS["RED_ORANGE"]],
            ["chores fol", COLORS["ORANGE"]],
            ["work fol", COLORS["CORAL"]],
            ["misc fol", COLORS["LIGHT_SALMON"]],
        ],
    },
}